### ISSUE TITLE
Gem install failure with Ruby 2.6 and ruby-opencv-0.0.18

### ISSUE THREAD

**Issue by justinschier** [ruby-opencv/ruby-opencv#103]
I've had no problem installing when using Ruby 2.5.1.

But now I am upgrading to Ruby 2.6.2 and ruby-opencv 0.0.18 fails to install.

Relevant output from bundle install:

Fetching ruby-opencv 0.0.18
Installing ruby-opencv 0.0.18 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/lib/ruby/gems/2.6.0/gems/ruby-opencv-0.0.18/ext/opencv
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20190415-9-1mh74ct.rb extconf.rb
>> Check the required libraries...
checking for -lstdc++... yes
checking for -lopencv_calib3d... yes
checking for -lopencv_contrib... yes
checking for -lopencv_core... yes
checking for -lopencv_features2d... yes
checking for -lopencv_flann... yes
checking for -lopencv_highgui... yes
checking for -lopencv_imgproc... yes
checking for -lopencv_legacy... yes
checking for -lopencv_ml... yes
checking for -lopencv_objdetect... yes
checking for -lopencv_video... yes
checking for -lopencv_photo... yes
checking for -lopencv_gpu... yes
checking for -lopencv_nonfree... no
opencv_nonfree not found.
>> Check the required headers...
checking for opencv2/core/core_c.h... yes
checking for opencv2/core/core.hpp... yes
checking for opencv2/imgproc/imgproc_c.h... yes
checking for opencv2/imgproc/imgproc.hpp... yes
checking for opencv2/video/tracking.hpp... yes
checking for opencv2/features2d/features2d.hpp... yes
checking for opencv2/flann/flann.hpp... yes
checking for opencv2/calib3d/calib3d.hpp... yes
checking for opencv2/objdetect/objdetect.hpp... yes
checking for opencv2/legacy/compat.hpp... yes
checking for opencv2/legacy/legacy.hpp... yes
checking for opencv2/highgui/highgui_c.h... yes
checking for opencv2/highgui/highgui.hpp... yes
checking for opencv2/photo/photo.hpp... yes
checking for opencv2/nonfree/nonfree.hpp... no
opencv2/nonfree/nonfree.hpp not found.
checking for stdarg.h... yes
creating Makefile

current directory:
/usr/local/lib/ruby/gems/2.6.0/gems/ruby-opencv-0.0.18/ext/opencv
make "DESTDIR=" clean

current directory:
/usr/local/lib/ruby/gems/2.6.0/gems/ruby-opencv-0.0.18/ext/opencv
make "DESTDIR="
compiling algorithm.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling curve.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvavgcomp.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvbox2d.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvcapture.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvchain.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvcircle32f.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvconnectedcomp.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvcontour.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvcontourtree.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvconvexitydefect.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cverror.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cverror.cpp: In function ‘void mOpenCV::cCvError::raise(cv::Exception)’:
cverror.cpp:46:1: warning: function might be candidate for attribute ‘noreturn’
[-Wsuggest-attribute=noreturn]
 raise(cv::Exception e)
 ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvfeaturetree.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvfont.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvhaarclassifiercascade.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
compiling cvhistogram.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but
not for C++
In file included from /usr/local/include/ruby-2.6.0/ruby.h:33:0,
                 from opencv.h:17,
                 from cvhistogram.h:13,
                 from cvhistogram.cpp:10:
cvhistogram.cpp: In function ‘VALUE mOpenCV::cCvHistogram::rb_initialize(int,
VALUE*, VALUE)’:
cvhistogram.cpp:98:20: error: expected primary-expression before ‘int’
   sizes = ALLOCA_N(int, sizes_len);
                    ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:98:11: note: in expansion of macro ‘ALLOCA_N’
   sizes = ALLOCA_N(int, sizes_len);
           ^
cvhistogram.cpp:105:23: error: expected primary-expression before ‘float’
     ranges = ALLOCA_N(float*, sizes_len);
                       ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
cvhistogram.cpp:110:53: error: expected primary-expression before ‘float’
       ranges[i] = ary2fltptr(range_ptr[i], ALLOCA_N(float, 2));
                                                     ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
cvhistogram.cpp: In function ‘VALUE
mOpenCV::cCvHistogram::rb_calc_hist_bang(int, VALUE*, VALUE)’:
cvhistogram.cpp:199:37: error: expected primary-expression before ‘*’ token
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                                     ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: expected
primary-expression before ‘)’ token
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:199:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:199:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
cvhistogram.cpp: In function ‘VALUE mOpenCV::cCvHistogram::rb_aref(VALUE,
VALUE)’:
cvhistogram.cpp:231:23: error: expected primary-expression before ‘int’
   int* idx = ALLOCA_N(int, num_idx);
                       ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:231:14: note: in expansion of macro ‘ALLOCA_N’
   int* idx = ALLOCA_N(int, num_idx);
              ^
cvhistogram.cpp: In function ‘VALUE
mOpenCV::cCvHistogram::rb_min_max_value(VALUE)’:
cvhistogram.cpp:284:24: error: expected primary-expression before ‘int’
     min_idx = ALLOCA_N(int, dims);
                        ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:284:15: note: in expansion of macro ‘ALLOCA_N’
     min_idx = ALLOCA_N(int, dims);
               ^
cvhistogram.cpp:285:24: error: expected primary-expression before ‘int’
     max_idx = ALLOCA_N(int, dims);
                        ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
cvhistogram.cpp: In function ‘VALUE
mOpenCV::cCvHistogram::rb_set_hist_bin_ranges_bang(int, VALUE*, VALUE)’:
cvhistogram.cpp:498:29: error: expected primary-expression before ‘float’
   float** ranges = ALLOCA_N(float*, ranges_size);
                             ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:498:20: note: in expansion of macro ‘ALLOCA_N’
   float** ranges = ALLOCA_N(float*, ranges_size);
                    ^
cvhistogram.cpp:501:51: error: expected primary-expression before ‘float’
     ranges[i] = ary2fltptr(range_ptr[i], ALLOCA_N(float, 2));
                                                   ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
cvhistogram.cpp: In function ‘VALUE
mOpenCV::cCvHistogram::rb_calc_back_project(VALUE, VALUE)’:
cvhistogram.cpp:535:37: error: expected primary-expression before ‘*’ token
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                                     ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: expected
primary-expression before ‘)’ token
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:535:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:535:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
cvhistogram.cpp: In function ‘VALUE
mOpenCV::cCvHistogram::rb_calc_back_project_patch(VALUE, VALUE, VALUE, VALUE,
VALUE)’:
cvhistogram.cpp:582:37: error: expected primary-expression before ‘*’ token
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                                     ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:22: note: in definition of macro
‘ALLOCA_N’
         RUBY_ALIGNOF(type) * CHAR_BIT)
                      ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: expected
primary-expression before ‘)’ token
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:582:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
/usr/local/include/ruby-2.6.0/ruby/ruby.h:1667:26: error: ‘alignof’ was not
declared in this scope
         RUBY_ALIGNOF(type) * CHAR_BIT)
                          ^
cvhistogram.cpp:582:20: note: in expansion of macro ‘ALLOCA_N’
   IplImage** img = ALLOCA_N(IplImage*, num_images);
                    ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option
‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
Makefile:235: recipe for target 'cvhistogram.o' failed
make: *** [cvhistogram.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/usr/local/lib/ruby/gems/2.6.0/gems/ruby-opencv-0.0.18 for inspection.
Results logged to
/usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0-static/ruby-opencv-0.0.18/gem_make.out

An error occurred while installing ruby-opencv (0.0.18), and Bundler cannot
continue.
Make sure that `gem install ruby-opencv -v '0.0.18' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  ruby-opencv

**Comment by ronanmcnulty** [comment]
Did you get this working with 2.6?

**Comment by barrywoolgar** [comment]
Hi @justinschier, did you figure this out? Cheers

**Comment by justinschier** [comment]
No, unfortunately we had to get rid of opencv.

**Comment by Lykos** [comment]
I got a similar error with a completely different gem here:
https://github.com/Lykos/cube_trainer/runs/451697504

If anyone knows how to fix it, I would be interested.

**Comment by barrywoolgar** [comment]
If the errors _are_ similar, then I think it would be better if you created an issue on that gem, and reference this one, stating why you think they're similar. Then both communities can benefit from any possible solutions.

However, and I'm no C expert, I think the extent of the similarity is just a failure to compile - is there a common root failure that you can see between these two logs that I'm missing?

**Comment by Lykos** [comment]
Yes, both have trouble compiling specifically because of the RUBY_ALIGNOF macro in ruby.h that expands to "alignof". So it seems to be the same compile error.

I will also create an issue on that gem, but I thought this issue may also benefit from the knowledge that it's possibly not only a problem of this specific gem.

**Comment by syun03** [comment]
Replace from ALLOCA_N to RB_ALLOC_N .
It worked as expected on ruby 2.3.1 and ruby 2.6.6 .
but ruby-2.7.1 not work

c477d20

**Comment by barrywoolgar** [comment]
Thank you @syun03 and @ser1zw - this PR has allowed me to upgrade to Ruby 2.6.6, and bought me a little time to upgrade from OpenCV 2 to something more recent! 

I'm using OSX with OpenCV installed via `brew`, so I had to run the following to resolve `Library not loaded` errors:

```
brew uninstall opencv@2
brew install opencv@2
brew link opencv@2 --force
```

**Comment by kopylovvlad** [comment]
@ser1zw Could you please bump version of gem and upload it to rubygems?

I use ruby-2.6.5 and can't install the gem from rubygems because there is latest version from March 06, 2017. [Fix for ruby-2.5.x](https://github.com/ruby-opencv/ruby-opencv/commit/c477d204b1e243ecdbe697ff6f25795556656531) is merged on  29 Jul 2018 .
